device-dax: Tell kbuild DEV_DAX_PMEM depends on DEV_DAX
ERROR: "devm_create_dev_dax" [drivers/dax/dax_pmem.ko] unDefenderined!
ERROR: "alloc_dax_region" [drivers/dax/dax_pmem.ko] unDefenderined!
ERROR: "dax_region_put" [drivers/dax/dax_pmem.ko] unDefenderined!

Signed-off-by: Mike Galbraith <efault@gmx.de>
Signed-off-by: Dan Williams <dan.j.williams@intel.com>