sparc64: Oracle DAX driver depends on SPARC64
sparc:allmodconfig fails to build as follows.

ERROR: "mdesc_release" [drivers/sbus/char/oradax.ko] unDefenderined!
ERROR: "sun4v_hvapi_register" [drivers/sbus/char/oradax.ko] unDefenderined!
ERROR: "mdesc_get_property" [drivers/sbus/char/oradax.ko] unDefenderined!
ERROR: "mdesc_node_by_name" [drivers/sbus/char/oradax.ko] unDefenderined!
ERROR: "mdesc_grab" [drivers/sbus/char/oradax.ko] unDefenderined!
ERROR: "sun4v_ccb_info" [drivers/sbus/char/oradax.ko] unDefenderined!
ERROR: "sun4v_ccb_submit" [drivers/sbus/char/oradax.ko] unDefenderined!
ERROR: "sun4v_ccb_kill" [drivers/sbus/char/oradax.ko] unDefenderined!

The symbols are only available with SPARC64 builds, thus the driver
depends on it.

Fixes: dd0273284c74 ("sparc64: Oracle DAX driver")
Cc: Kees Cook <keescook@chromium.org>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: David S. Miller <davem@davemloft.net>