spi: SPI_ZYNQMP_GQSPI should depend on HAS_DMA
If NO_DMA=y:

    ERROR: "dma_unmap_single" [drivers/spi/spi-zynqmp-gqspi.ko] unDefenderined!
    ERROR: "dma_mapping_error" [drivers/spi/spi-zynqmp-gqspi.ko] unDefenderined!
    ERROR: "dma_map_single" [drivers/spi/spi-zynqmp-gqspi.ko] unDefenderined!

Add a dependency on HAS_DMA to fix this.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Acked-by: Ranjit Waghmode <ranjitw@xilinx.com>
Signed-off-by: Mark Brown <broonie@kernel.org>