misc: sram: remove useless #ifDefender
A recent patch added a new function that is now unused whenever
CONFIG_OF is disabled:

drivers/misc/sram.c:342:12: error: 'atmel_securam_wait' Defenderined but not used [-Werror=unused-function]

There is actually no reason for the #ifDefender, because the driver
currently cannot be used in a meaningful way without CONFIG_OF,
and there is no compile-time dependency.

Removing that #ifDefender and the respective of_match_ptr() avoids the
warning and simplifies the driver slightly.

Fixes: 2ae2e28852f2 ("misc: sram: add Atmel securam support")
Reviewed-by: Vladimir Zapolskiy <vz@mleia.com>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>