ANDROID: Fix kernelci build-break for arm32
Fixes recent build-break for arm32 builds:

drivers/gpio/gpiolib.c:1925:26: error: implicit declaration of
function ‘irq_domain_add_hierarchy’; did you mean
‘irq_domain_is_hierarchy’?

Fixes: 4fd4604c8bf2 ("ANDROID: GKI: gpio: Add support for hierarchical
IRQ domains")
Signed-off-by: Todd Kjos <tkjos@google.com>
Change-Id: I972e8bc000a203dac30ce860a7f29c7309556602