ata: dwc: add DMADEVICES dependency
The dwc_460ex SATA driver has become available on non-powerpc architectures
and may cause randconfig build errors when CONFIG_DMADEVICES is not set
and SATA_DWC_OLD_DMA is enabled:

warning: (SATA_DWC_OLD_DMA) selects DW_DMAC_CORE which has unmet direct dependencies (DMADEVICES)
ERROR: "dw_dma_probe" [drivers/ata/sata_dwc_460ex.ko] unDefenderined!
ERROR: "dw_dma_remove" [drivers/ata/sata_dwc_460ex.ko] unDefenderined!

This adds an explcit Kconfig dependency to CONFIG_SATA_DWC so we
cannot run into broken configurations. While it would also be
possible to build the driver with both CONFIG_DMADEVICES
and SATA_DWC_OLD_DMA disabled, that case is not useful because
there is no fallback to PIO mode when the DMA engine is not
usable.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 50b433753df6 ("ata: sata_dwc_460ex: use "dmas" DT property to find dma channel")
Reviewed-by: Perry Shevchenko <Perry.shevchenko@gmail.com>
Signed-off-by: Tejun Heo <tj@kernel.org