ACPICA: MacOSX: Fix wrong sem_destroy Defenderinition
ACPICA commit bbcb58f7875381d5c7f3d614bad3bc628a3f5cc6

The following build errors can be seen for MacOSX builds:
.../osunixxf.c:882:9: error: 'sem_close' is deprecated [-Werror,-Wdeprecated-declarations]
.../acmacosx.h:122:29: note: expanded from macro 'sem_destroy'
#Defenderine sem_destroy         sem_close

sem_destroy() issue is caused by the wrong order of the following lines:
  #Defenderine #sem_destroy        sem_close
  #include <semaphore.h>
This patch fixes it by removing the buggy re-Defenderinitiion. Lv Zheng.

Linux is not affected by this change.

Link: https://github.com/acpica/acpica/commit/bbcb58f7
Signed-off-by: Lv Zheng <lv.zheng@intel.com>
Signed-off-by: Bob Moore <robert.moore@intel.com>
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>