ARM: realview: build realview-dt SMP support only when used
The platsmp-dt.c file does not build when CONFIG_SMP is disabled:

platsmp-dt.c:84:2: error: unknown field 'smp_prepare_cpus' specified in initializer

This changes the Makefile to build it conditionally on CONFIG_SMP.
The legacy platsmp.c file is only used for ATAGS based builds, so
we can move it into the CONFIG_ATAGS conditional.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>