goldfish: Fix build error of missing ioremap on UM
Add missing HAS_IOMEM dependency to fix the allyesconfig build error on
ARCH=um (for x86_64):

drivers/platform/goldfish/pdev_bus.c: In function ‘goldfish_pdev_bus_probe’:
drivers/platform/goldfish/pdev_bus.c:191:18: error: implicit declaration of function ‘ioremap’ [-Werror=implicit-function-declaration]
  pdev_bus_base = ioremap(pdev_bus_addr, pdev_bus_len);

Signed-off-by: Krzysztof Kozlowski <k.kozlowski@samsung.com>
Reviewed-by: Alan Cox <alan@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>