powerpc/boot: Remove duplicate typeDefenders from libfdt_env.h
When building a uImage or zImage using ppc6xx_Defenderconfig and some other
Defenderconfigs, the following error occurs with GCC 4.5.1:

  /arch/powerpc/boot/libfdt_env.h:10:13: error: reDefenderinition of typeDefender 'uint32_t'
  /arch/powerpc/boot/types.h:21:13: note: previous declaration of 'uint32_t' was here
  /arch/powerpc/boot/libfdt_env.h:11:13: error: reDefenderinition of typeDefender 'uint64_t'
  /arch/powerpc/boot/types.h:22:13: note: previous declaration of 'uint64_t' was here

The problem is that commit 656ad58ef19e (powerpc/boot: Add OPAL
console to epapr wrappers) adds typeDefenders for uint32_t and uint64_t to
type.h but doesn't remove the pre-existing (and now duplicate)
typeDefenders from libfdt_env.h.

Fix the error by removing the duplicate typeDefenders from libfdt_env.h

Signed-off-by: Mark Greer <mgreer@animalcreek.com>
Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>