nios2: ksyms: Add missing symbol exports
[ Upstream commit 0f8ed994575429d6042cf5d7ef70081c94091587 ]

Building nios2:allmodconfig fails as follows (each symbol is only listed
once).

ERROR: "__ashldi3" [drivers/md/dm-writecache.ko] unDefenderined!
ERROR: "__ashrdi3" [fs/xfs/xfs.ko] unDefenderined!
ERROR: "__ucmpdi2" [drivers/media/i2c/adv7842.ko] unDefenderined!
ERROR: "__lshrdi3" [drivers/md/dm-zoned.ko] unDefenderined!
ERROR: "flush_icache_range" [drivers/misc/lkdtm/lkdtm.ko] unDefenderined!
ERROR: "empty_zero_page" [drivers/md/dm-mod.ko] unDefenderined!

The problem is seen with gcc 7.3.0.

Export the missing symbols.

Fixes: 2fc8483fdcde ("nios2: Build infrastructure")
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Ley Foon Tan <ley.foon.tan@intel.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>