net: ppp: Fix modular build for PPPOLAC and PPPOPNS
Unlike other configurations in net/ppp, PPPOLAC and PPPOPNS
are Defenderined as boolean configuration options. In allmodconfig builds
(or, specifically, if PPP and some of the other PPP protocols were
built as modules), this resulted in build errors such as the following,
since pppox was built both as module and into the kernel.

ERROR: "pppox_ioctl" [net/l2tp/l2tp_ppp.ko] unDefenderined!
ERROR: "unregister_pppox_proto" [net/l2tp/l2tp_ppp.ko] unDefenderined!
ERROR: "register_pppox_proto" [net/l2tp/l2tp_ppp.ko] unDefenderined!
ERROR: "pppox_unbind_sock" [net/l2tp/l2tp_ppp.ko] unDefenderined!

Fix the problem by Defenderining PPPOLAC and PPPOPNS tristate.

Signed-off-by: Guenter Roeck <groeck@chromium.org>