abi: add the filp_open symbol whitelist for utags modules
After rebase Qcom drop r.0011 (LA.UM.9.14.r1-10500-LAHAINA.0-1), Qcom kernel
removed the filp_open/filp_close symbols and causes the utags module compile
error.
  ERROR: "filp_close" [../../motorola/kernel/modules/drivers/misc/utag/utags.ko] undefined!
  ERROR: "filp_open" [../../motorola/kernel/modules/drivers/misc/utag/utags.ko] undefined!

Add back the symbols back to whitelist because they are in the Google whitelist.

Change-Id: Icffa6ed5c66e3aef2243da46a60ba7a5b7192dca
Reviewed-on: https://gerrit.mot.com/1797040
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Guobin Zhang <zhanggb@motorola.com>
Submit-Approved: Jira Key