ANDROID: dma-buf/sw_sync: Rename active_list to link
Upstream commit d3862e44daa7 ("dma-buf/sw-sync: Fix locking around
sync_timeline lists") renamed sync_pt -> active_list to -> link and we
run into folowing build error:

drivers/dma-buf/sw_sync.c:176:19: error: 'struct sync_pt' has no member named 'active_list'

Reported at KernelCI:
https://kernelci.org/build/android/branch/android-4.9/kernel/ASB-2017-11-06_4.9-o-release-1566-gfdeec8fdb714/

Fixes: Change-Id: I05c34dcf74438c28405438c7ead0706b1f810fff
       ("CHROMIUM: android: fix warning when releasing active sync point")
Signed-off-by: Amit Pundir <amit.pundir@linaro.org>