cifs: hide unused functions
Some functions are only referenced under an #ifDefender, causing a harmless
warning:

fs/cifs/smb2ops.c:1374:1: error: 'get_smb2_acl' Defenderined but not used [-Werror=unused-function]

We could mark them __maybe_unused or add another #ifDefender, I picked
the second approach here.

Fixes: b3fdda4d1e1b ("cifs: Use smb 2 - 3 and cifsacl mount options getacl functions")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Steve French <smfrench@gmail.com>