ARM: realview: hide unused 'pmu_device' object
The pmu_device is only accessed when CACHE_L2X0 is enabled,
and we get a warning otherwise:

mach-realview/realview_pbx.c:274:31: error: 'pmu_device' Defenderined but not used [-Werror=unused-variable]

This adds another #ifDefender for it.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Linus Walleij <linus.walleij@linaro.org>