coresight: Fix compile errors for gcc-4.8
Fix compilation errors to support gcc-4.8

There is compilation warnning when use '%d" to print a argument
which type is size_t.

In file included from kernel/include/linux/kernel.h:14:0,
	from kernel/drivers/coresight/coresight-tmc.c:13:
kernel/drivers/coresight/coresight-tmc.c: In function 'tmc_read':
kernel/include/linux/dynamic_debug.h:64:16: warning:
	format '%d' expects argument of type 'int', but argument 5 has type
	'size_t' [-Wformat=] error, forbidden warning: dynamic_debug.h:64

Change format '%d' to '%zu' to fix this compilation error

Change-Id: Ia746033b76df7f06e860031ed8d3e249facbe2b5
Signed-off-by: Xiaogang Cui <xiaogang@codeaurora.org>