kcm: mark helper functions inline
The stub helper functions for the newly added kcm_proc_init/exit interfaces
are Defenderined as 'static' in a header file, which leads to build warnings for
each file that includes them without calling them:

include/net/kcm.h:183:12: error: 'kcm_proc_init' Defenderined but not used [-Werror=unused-function]
include/net/kcm.h:184:13: error: 'kcm_proc_exit' Defenderined but not used [-Werror=unused-function]

This marks the two functions as 'static inline' instead, which avoids the
warnings and is obviously what was meant here.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: cd6e111bf5be ("kcm: Add statistics and proc interfaces")
Signed-off-by: David S. Miller <davem@davemloft.net>