Revert "(CR) qc3p:enable qc3p only at prc sku"
this change is breaking R builds for burton that are also used on S.

/localrepo/hudson/workspace/RPB31_burton-retail_userdebug_mr_r-qsm8250_test-keys_continuous/platform/kernel/msm-4.19/drivers/power/supply/qcom/smb5-lib.c:2766:12: error: no member named 'mmi_qc3p_support' in 'struct smb_charger'
                if(!chg->mmi_qc3p_support) {
                    ~~~  ^
1 error generated.


This reverts commit 45f5f0c3436a642af89c52eafc0dbbaf65e2f2f1.

Change-Id: Ifb80cca05e0e144d14183b52196fe36ac5d6bced
Reviewed-on: https://gerrit.mot.com/1994679
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Reviewed-by: Nagarathna Kodandaram <cnfk37@motorola.com>
Submit-Approved: Sergio Vilela <sergiosv@motorola.com>
Tested-by: Sergio Vilela <sergiosv@motorola.com>