msm: sde: fix for 32-bit build '__udivdi3' error
Undefined reference to '__udivdi3' error happened
for 32bit build. Change from DIV_ROUND_UP to DIV_ROUND_UP_SECTOR_T
which can take care of different BITS_PER_LONG.

Change-Id: Iedbfa1b8d4ae68fe2b03ebe8464b974c891e7bec
Signed-off-by: Maria Yu <aiquny@codeaurora.org>