staging: most: fix aim-network build errors
Fix build errors when CONFIG_NET is not enabled by making the driver
depend on NET.
Also correct the loadable module name.

ERROR: "__netdev_alloc_skb" [drivers/staging/most/aim-network/aim_network.ko] undefined!
ERROR: "netif_rx" [drivers/staging/most/aim-network/aim_network.ko] undefined!
ERROR: "netif_tx_wake_queue" [drivers/staging/most/aim-network/aim_network.ko] undefined!
ERROR: "free_netdev" [drivers/staging/most/aim-network/aim_network.ko] undefined!
ERROR: "register_netdev" [drivers/staging/most/aim-network/aim_network.ko] undefined!
ERROR: "kfree_skb" [drivers/staging/most/aim-network/aim_network.ko] undefined!
ERROR: "alloc_netdev_mqs" [drivers/staging/most/aim-network/aim_network.ko] undefined!
ERROR: "eth_type_trans" [drivers/staging/most/aim-network/aim_network.ko] undefined!
ERROR: "ether_setup" [drivers/staging/most/aim-network/aim_network.ko] undefined!
ERROR: "unregister_netdev" [drivers/staging/most/aim-network/aim_network.ko] undefined!
ERROR: "skb_put" [drivers/staging/most/aim-network/aim_network.ko] undefined!
ERROR: "eth_mac_addr" [drivers/staging/most/aim-network/aim_network.ko] undefined!

Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Cc: Andrey Shvetsov <andrey.shvetsov@k2l.de>
Cc: Michael Fabry <Michael.Fabry@microchip.com>
Acked-by: Christian Gromm <christian.gromm@microchip.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>