ethernet: qualcomm: QCOM_EMAC should depend on HAS_DMA and HAS_IOMEM
If NO_DMA=y:

    drivers/built-in.o: In function `emac_probe':
    emac.c:(.text+0x3780b8): unDefenderined reference to `bad_dma_ops'
    emac.c:(.text+0x3780e2): unDefenderined reference to `bad_dma_ops'
    emac.c:(.text+0x378112): unDefenderined reference to `bad_dma_ops'
    emac.c:(.text+0x378146): unDefenderined reference to `bad_dma_ops'
    emac.c:(.text+0x37816e): unDefenderined reference to `bad_dma_ops'
    drivers/built-in.o:emac.c:(.text+0x37819a): more unDefenderined references to `bad_dma_ops' follow

If NO_IOMEM=y:

    drivers/net/ethernet/qualcomm/emac/emac.c: In function ‘emac_remove’:
    drivers/net/ethernet/qualcomm/emac/emac.c:736:3: error: implicit declaration of function ‘iounmap’ [-Werror=implicit-function-declaration]
       iounmap(adpt->phy.digital);
       ^

Add dependencies on HAS_DMA and HAS_IOMEM to fix this.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Acked-by: Timur Tabi <timur@codeaurora.org>
Signed-off-by: David S. Miller <davem@davemloft.net>