ANDROID: Fix kernelci break: eventfd_signal_mask redefined
Fix a merge issue where eventfd_signal_mask() was added twice which
resulted in kernelci issues when !CONFIG_EVENTFD:

include/linux/eventfd.h:76:19: error: redefinition of ‘eventfd_signal_mask’

Fixes: 4ef66581d7fd ("eventfd: provide a eventfd_signal_mask() helper")
Signed-off-by: Todd Kjos <tkjos@google.com>
Change-Id: Ifdd212e857c2ff76c75283e77b9978e51a96d178