Fix build error caused by aw869xx kernel module
ERROR: "i2c_smbus_write_byte_data" [../../motorola/kernel/modules/drivers/misc/awinic/aw869xx/aw869xx.ko] undefined!
ERROR: "i2c_smbus_read_byte_data" [../../motorola/kernel/modules/drivers/misc/awinic/aw869xx/aw869xx.ko] undefined!

Change-Id: Ia4a5ff55dee9c9d6c5b4605b9eab5dca73e2cbf1
Signed-off-by: huangys <huangys@motorola.com>
Reviewed-on: https://gerrit.mot.com/1727232
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Zhenxin Xi <xizx@motorola.com>
Submit-Approved: Jira Key