CHROMIUM: usb: gadget: f_mtp: Declare unused functions as maybe_unused
Without this, we get these 2 warnings:
v3.18/drivers/usb/gadget/function/f_mtp.c:1289:12: error: 'mtp_bind_config' defined but not used [-Werror=unused-function]
 static int mtp_bind_config(struct usb_configuration *c, bool ptp_config)
            ^
v3.18/drivers/usb/gadget/function/f_mtp.c:1372:12: error: 'mtp_setup' defined but not used [-Werror=unused-function]
 static int mtp_setup(void)
            ^
cc1: all warnings being treated as errors

Arguably, the functions could be removed, but it looks like the
intent of drivers/usb/gadget/android.c is to include these, so
leave them be.

BUG=chromium:534254
TEST=emerge-smaug chromeos-kernel-3_18

Change-Id: Ie1b10d91b69b75ab2543e939e51fa9d74a64b950
Signed-off-by: Nicolas Boichat <drinkcat@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/300705
Reviewed-by: Benson Leung <bleung@chromium.org>