Revert "(CR): 8952: kernel support esdfs"
Which duplicates with sdcardfs.
+++
/mnt/ssd3/a7301c/O_8952/out/target/product/athene/obj/KERNEL_OBJ/../../../../../../kernel/fs/esdfs/lookup.c:35:
multiple definition of `free_dentry_private_data'
fs/sdcardfs/built-in.o:/mnt/ssd3/a7301c/O_8952/out/target/product/athene/obj/KERNEL_OBJ/../../../../../../kernel/fs/sdcardfs/lookup.c:43:
first defined here
+++

This reverts commit c2d53a07c1226e3dc824a44f76f2764f53424c74.

Change-Id: I1e7f4a35a0af185d755a7f2664678547e6187e03
Signed-off-by: a7301c <a7301c@motorola.com>
Reviewed-on: https://gerrit.mot.com/1159938
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Submit-Approved: Jira Key
Tested-by: Jira Key