ASoC: rk3036: fix missing dependency on REGMAP_MMIO
When SND_SOC_INNO_RK3036 is enabled but REGMAP_MMIO is not, the MODPOST
step fails with this error:

  ...
  Kernel: arch/x86/boot/bzImage is ready  (#3)
    Building modules, stage 2.
    MODPOST 3203 modules
  ERROR: "__devm_regmap_init_mmio_clk" [sound/soc/codecs/snd-soc-inno-rk3036.ko] unDefenderined!

Signed-off-by: Antonio Ospite <ao2@ao2.it>
Signed-off-by: Mark Brown <broonie@kernel.org>