ata: ATA_BMDMA should depend on HAS_DMA
If NO_DMA=y:

    ERROR: "dmam_alloc_coherent" [drivers/ata/libata.ko] unDefenderined!

Add a dependency on HAS_DMA to fix this.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Signed-off-by: Tejun Heo <tj@kernel.org>