Fugu clean-up: Fix compilation warning
BZ: 209177

drivers/platform/x86/intel_scu_ipcutil.c:1743:12: error:
'intel_scu_ipc_read_oemnib' defined but not used [-Werror=unused-function]

Change-Id: I5c6f592a6c80fd8a45c8ae3e887291e9cdd664ed
Signed-off-by: Olivier Fourdan <olivier.fourdan@intel.com>
Reviewed-on: https://android.intel.com/216932
Reviewed-by: Koskinen, Ilkka <ilkka.koskinen@intel.com>