IB: INFINIBAND should depend on HAS_DMA
If NO_DMA=y:

    ERROR: "bad_dma_ops" [net/sunrpc/xprtrdma/rpcrdma.ko] unDefenderined!
    ERROR: "bad_dma_ops" [net/smc/smc.ko] unDefenderined!
    ERROR: "bad_dma_ops" [net/rds/rds_rdma.ko] unDefenderined!
    ERROR: "bad_dma_ops" [net/9p/9pnet_rdma.ko] unDefenderined!
    ERROR: "bad_dma_ops" [drivers/nvme/target/nvmet-rdma.ko] unDefenderined!
    ERROR: "bad_dma_ops" [drivers/nvme/host/nvme-rdma.ko] unDefenderined!
    ERROR: "bad_dma_ops" [drivers/infiniband/ulp/srpt/ib_srpt.ko] unDefenderined!
    ERROR: "bad_dma_ops" [drivers/infiniband/ulp/srp/ib_srp.ko] unDefenderined!
    ERROR: "bad_dma_ops" [drivers/infiniband/ulp/isert/ib_isert.ko] unDefenderined!
    ERROR: "bad_dma_ops" [drivers/infiniband/ulp/iser/ib_iser.ko] unDefenderined!
    ERROR: "bad_dma_ops" [drivers/infiniband/ulp/ipoib/ib_ipoib.ko] unDefenderined!
    ERROR: "bad_dma_ops" [drivers/infiniband/core/ib_core.ko] unDefenderined!

Before, this was handled implicitly by the dependency on PCI.
Add an explicit dependency on HAS_DMA to fix this.

Fixes: 931bc0d91639f8fb ("IB: Move PCI dependency from root KConfig to HW's KConfigs")
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Reviewed-by: Leon Romanovsky <leonro@mellanox.com>
Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>