Revert "kernel: lib: allow larger stack frame size for KASan"
This reverts commit 8bb334401c84
("kernel: lib: allow larger stack frame size for KASan").

Stack frame size set to 5600 to fix compilation error/s if
KASAN enabled by the commit 8bb334401c84 ("kernel: lib: allow
larger stack frame size for KASan") in 3.18 Kernel and same
commit got pulled into Kernel 4.4, which replaced stack
frame size 0 with 5600 as part of resolution of merge conflict.
But, by setting stack frame size to 0 will ignore stack frame
size warnings and so the compilation errors. So, revert commit
to fix below error while compiling Kernel 4.4 with KASAN enabled
and GCC 5.1 compiler.

kernel/net/wireless/nl80211.c: In function 'nl80211_send_wiphy':
kernel/net/wireless/nl80211.c:1745:1: warning: the frame size of \
5760 bytes is larger than 5600 bytes [-Wframe-larger-than=]
error, forbidden warning: nl80211.c:1745
make[4]: *** [net/wireless/nl80211.o] Error 1

CRs-Fixed: 1004225
Change-Id: I97e52302197c9933bec5cac3ebdc4ec73fee0816
Signed-off-by: Satya Durga Srinivasu Prabhala <satyap@codeaurora.org>