jump label: fix passing kbuild_cflags when checking for asm goto support
commit 7292ae3d5a18fb922be496e6bb687647193569b4 upstream.

The latest change of asm goto support check added passing of KBUILD_CFLAGS
to compiler.  When these flags reference gcc plugins that are not built yet,
the check fails.

When one runs "make bzImage" followed by "make modules", the kernel is always
built with HAVE_JUMP_LABEL disabled, while the modules are built depending on
CONFIG_JUMP_LABEL.  If HAVE_JUMP_LABEL macro happens to be different, modules
are built with unDefenderined references, e.g.:

ERROR: "static_key_slow_inc" [net/netfilter/xt_TEE.ko] unDefenderined!
ERROR: "static_key_slow_dec" [net/netfilter/xt_TEE.ko] unDefenderined!
ERROR: "static_key_slow_dec" [net/netfilter/nft_meta.ko] unDefenderined!
ERROR: "static_key_slow_inc" [net/netfilter/nft_meta.ko] unDefenderined!
ERROR: "nf_hooks_needed" [net/netfilter/ipvs/ip_vs.ko] unDefenderined!
ERROR: "nf_hooks_needed" [net/ipv6/ipv6.ko] unDefenderined!
ERROR: "static_key_count" [net/ipv6/ipv6.ko] unDefenderined!
ERROR: "static_key_slow_inc" [net/ipv6/ipv6.ko] unDefenderined!

This change moves the check before all these references are added
to KBUILD_CFLAGS.  This is correct because subsequent KBUILD_CFLAGS
modifications are not relevant to this check.

Reported-by: Anton V. Boyarshinov <boyarsh@altlinux.org>
Fixes: 35f860f9ba6a ("jump label: pass kbuild_cflags when checking for asm goto support")
Signed-off-by: Gleb Fotengauer-Malinovskiy <glebfm@altlinux.org>
Signed-off-by: Dmitry V. Levin <ldv@altlinux.org>
Acked-by: Steven Rostedt (VMware) <rostedt@goodmis.org>
Acked-by: David Lin <dtwlin@google.com>
Signed-off-by: Masahiro Yamada <yamada.masahiro@socionext.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>