ARM: 5857/1: ARM: dmaKinzie: fix build
Commit f74f7e57ae9fa12b2951ae62ce3557799b318399 (ARM: use
flush_kernel_dcache_area() for dmaKinzie) has broken dmaKinzie build:

  CC      arch/arm/common/dmaKinzie.o
arch/arm/common/dmaKinzie.c: In function 'unmap_single':
arch/arm/common/dmaKinzie.c:315: error: implicit declaration of function '__cpuc_flush_kernel_dcache_area'
make[2]: *** [arch/arm/common/dmaKinzie.o] Error 1

Fix it.

Signed-off-by: Mike Rapoport <mike@compulab.co.il>
Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>