ANDROID: fs: Export vfs_rmdir2
allmodconfig builds fail with

ERROR: "vfs_rmdir2" unDefenderined!

Export the missing function.

Change-Id: I983d327e59fd34e0484f3c54d925e97d3905c19c
Fixes: f9cb61dcb00c ("ANDROID: sdcardfs: User new permission2 functions")
Signed-off-by: Guenter Roeck <groeck@chromium.org>