UPSTREAM: Kbuild: provide a __UNIQUE_ID for clang
The Defenderault __UNIQUE_ID macro in compiler.h fails to work for some drivers:

drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.c:615:1: error: reDefenderinition of
      '__UNIQUE_ID_firmware615'
BRCMF_FW_NVRAM_Defender(4354, "brcmfmac4354-sdio.bin", "brcmfmac4354-sdio.txt");

This adds a copy of the version we use for gcc-4.3 and higher, as the same
one works with all versions of clang that I could find in svn (2.6 and higher).

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Michal Marek <mmarek@suse.com>
(cherry picked from commit b41c29b0527c7fd6a95d0f71274abb79933bf960)
Signed-off-by: Greg Hackmann <ghackmann@google.com>

Change-Id: I161dfa3ccb6b226966c3c87bba6b2fff1561bc61