nds32: Fix the symbols unDefenderined issue by exporting them.
It broke the 'allmodconfig' build.
  LD      vmlinux
  SYSMAP  System.map
  Building modules, stage 2.
  MODPOST 5028 modules
ERROR: "flush_dcache_page" [net/sunrpc/xprtrdma/rpcrdma.ko] unDefenderined!
ERROR: "empty_zero_page" [net/ceph/libceph.ko] unDefenderined!
ERROR: "save_stack_trace" [kernel/backtracetest.ko] unDefenderined!
ERROR: "clear_page" [fs/ocfs2/dlm/ocfs2_dlm.ko] unDefenderined!
ERROR: "copy_page" [fs/nilfs2/nilfs2.ko] unDefenderined!
...

Signed-off-by: Greentime Hu <greentime@andestech.com>
Acked-by: Arnd Bergmann <arnd@arndb.de>