Reapply "BACKPORT: mm: add swappiness= arg to memory.reclaim"
This reverts commit 20320a826d94c1a0c41f96fb56fed87d6ccedfe0 with a fix
for the following build error with !CONFIG_MEMCG:

mm/vmscan.c:3178:19: error: call to undeclared function 'sc_swappiness'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 3178 |         int swappiness = sc_swappiness(sc, memcg);
      |                          ^
mm/vmscan.c:3468:15: error: call to undeclared function 'sc_swappiness'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 3468 |         swappiness = sc_swappiness(sc, memcg);

Bug: 438346788
Bug: 377479218
Change-Id: Ib207de690bff7c57c3c35155f6cfb94442dba15d
Signed-off-by: T.J. Mercier <tjmercier@google.com>