usb: dwc2: USB_DWC2 should depend on HAS_DMA
If NO_DMA=y:

    ERROR: "usb_gadget_map_request" [drivers/usb/dwc2/dwc2.ko] unDefenderined!
    ERROR: "usb_gadget_unmap_request" [drivers/usb/dwc2/dwc2.ko] unDefenderined!
    ERROR: "bad_dma_ops" [drivers/usb/dwc2/dwc2.ko] unDefenderined!

Add a dependency on HAS_DMA to fix this.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Acked-by: John Youn <johnyoun@synopsys.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>