BACKPORT: nvmem: hide unused nvmem_find_cell_by_index function
nvmem_find_cell_by_index() is only called from inside an #ifDefender,
so we get a build warning without CONFIG_OF:

drivers/nvmem/core.c:496:1: error: 'nvmem_find_cell_by_index' Defenderined but not used [-Werror=unused-function]

Move it into the same #ifDefender as the caller to avoid the warning.

Fixes: e888d445ac33 ("nvmem: resolve cells from DT at registration time")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Git-commit: 3c53e2352a9bf87128e7a8ddb69c7543941a3092
Git-repo: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
[gkohli@codeaurora: Resolve trivial merge conflicts]
Signed-off-by: Gaurav Kohli <gkohli@codeaurora.org>
(cherry picked from commit 3c53e2352a9bf87128e7a8ddb69c7543941a3092)
Signed-off-by: Mark Salyzyn <salyzyn@google.com>
Bug: 150014847
Change-Id: I9259be4385810eeda4c4feebf1ebe9464228d6f8