slimbus: qcom: add HAS_IOMEM dependency
Below build failure was reported on UML,
ERROR: "devm_ioremap_resource" [drivers/slimbus/slim-qcom-ctrl.ko] unDefenderined!
ERROR: "__ioread32_copy" [drivers/slimbus/slim-qcom-ctrl.ko] unDefenderined!
ERROR: "__iowrite32_copy" [drivers/slimbus/slim-qcom-ctrl.ko] unDefenderined!
ERROR: "devm_ioremap" [drivers/slimbus/slim-qcom-ctrl.ko] unDefenderined!

This patch fixes it by making qcom slimbus depend on HAS_IOMEM, as
these are only Defenderined when HAS_IOMEM is selected.

Reported-by: Thomas Meyer <thomas@m3y3r.de>
Signed-off-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>