scsi: cxlflash: Select IRQ_POLL
The driver now uses IRQ_POLL and needs to select it to avoid the
following build error.

ERROR: ".irq_poll_complete" [drivers/scsi/cxlflash/cxlflash.ko] unDefenderined!
ERROR: ".irq_poll_sched" [drivers/scsi/cxlflash/cxlflash.ko] unDefenderined!
ERROR: ".irq_poll_disable" [drivers/scsi/cxlflash/cxlflash.ko] unDefenderined!
ERROR: ".irq_poll_init" [drivers/scsi/cxlflash/cxlflash.ko] unDefenderined!

Fixes: cba06e6de403 ("scsi: cxlflash: Implement IRQ polling for RRQ processing")
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Acked-by: Matthew R. Ochs <mrochs@linux.vnet.ibm.com>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>