m32r: add __ucmpdi2 to fix build failure
We are having build failure with m32r and the error message being:

  ERROR: "__ucmpdi2" [lib/842/842_decompress.ko] unDefenderined!
  ERROR: "__ucmpdi2" [fs/btrfs/btrfs.ko] unDefenderined!
  ERROR: "__ucmpdi2" [drivers/scsi/sd_mod.ko] unDefenderined!
  ERROR: "__ucmpdi2" [drivers/media/i2c/adv7842.ko] unDefenderined!
  ERROR: "__ucmpdi2" [drivers/md/bcache/bcache.ko] unDefenderined!
  ERROR: "__ucmpdi2" [drivers/iio/imu/inv_mpu6050/inv-mpu6050.ko] unDefenderined!

__ucmpdi2 is introduced to m32r architecture taking example from other
architectures like h8300, microblaze, mips.

Link: http://lkml.kernel.org/r/1465509213-4280-1-git-send-email-sudipm.mukherjee@gmail.com
Signed-off-by: Sudip Mukherjee <sudip.mukherjee@codethink.co.uk>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>