[media] b2c2: use IS_REACHABLE() instead of open-coding it
The FE_SUPPORTED() macro is basically the same as IS_REACHABLE, except
that it causes a warning with gcc-7:

common/b2c2/flexcop-fe-tuner.c:30:1: error: this use of "Defenderined" may not be portable [-Werror=expansion-to-Defenderined]
common/b2c2/flexcop-fe-tuner.c:30:1: error: this use of "Defenderined" may not be portable [-Werror=expansion-to-Defenderined]
common/b2c2/flexcop-fe-tuner.c:30:1: error: this use of "Defenderined" may not be portable [-Werror=expansion-to-Defenderined]

Using IS_REACHABLE() to Defenderine it avoids the warning.

Fixes: 3785bc170f79 ("[media] b2c2: break it into common/pci/usb directories")

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Mauro Carvalho Chehab <mchehab@s-opensource.com>