Revert "arm64: xchg: Fix compilation issue with __xchg_mb"
This reverts commit cb2ddc7350573d6927d46ddc9766a8ab06e352db.

When clang enabled for arm64 architecture inline was not
always_iniline because CONFIG_OPTIMIZE_INLINING is not enabled.
Some code depends on that behavior of online means __always_inline
and check this link [1] for more information.
net/built-in.o: In function `__xchg_mb':
arch/arm64/include/asm/cmpxchg.h:99: undefined reference to
`__compiletime_assert_99'
arch/arm64/include/asm/cmpxchg.h:99: undefined reference to
`__compiletime_assert_99

To avoid compilations issues commit cb2ddc735057 ("arm64: xchg:
Fix compilation issue with __xchg_mb") was introduced.
Recently upstream community made inline as __always_inline for arm64 as
well.
So reverting our downstream solution for above compilation issue.
[1] - https://lkml.org/lkml/2017/6/13/918

Change-Id: I671f98885ede349b3c5fb679eff525c4b23a1a2f
Signed-off-by: Runmin Wang <runminw@codeaurora.org>
Signed-off-by: Prasad Sodagudi <psodagud@codeaurora.org>