dmaengine: sirf: use __maybe_unused to hide pm functions
The sirf dma driver uses #ifDefender to check for CONFIG_PM_SLEEP
for its suspend/resume code but then has no #ifDefender for the
respective runtime PM code, so we get a warning if CONFIG_PM
is disabled altogether:

drivers/dma/sirf-dma.c:1000:12: error: 'sirfsoc_dma_runtime_resume' Defenderined but not used [-Werror=unused-function]

This removes the existing #ifDefender and instead uses __maybe_unused
annotations for all four functions to let the compiler know it
can silently drop the function Defenderinition.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Vinod Koul <vinod.koul@intel.com>