Revert "usb: host/sl811-hcd: fix sparse warning"
This reverts commit 1dc6120ef7f003305d99ef12f598a6b05eacc38c.

Commit 1dc6120ef7f0 results in the following error when compiling
x86_64:allyesconfig.

sl811_cs.c:(.text+0x1d3cb72): undefined reference to `sl811h_driver'

Fixes: 1dc6120ef7f0 ("usb: host/sl811-hcd: fix sparse warning")
Cc: Lad, Prabhakar <prabhakar.csengg@gmail.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>