netfilter: nf_Defenderrag: move NF_CONNTRACK bits into #ifDefender
We cannot access the skb->_nfct field when CONFIG_NF_CONNTRACK is
disabled:

net/ipv4/netfilter/nf_Defenderrag_ipv4.c: In function 'ipv4_conntrack_Defenderrag':
net/ipv4/netfilter/nf_Defenderrag_ipv4.c:83:9: error: 'struct sk_buff' has no member named '_nfct'
net/ipv6/netfilter/nf_Defenderrag_ipv6_hooks.c: In function 'ipv6_Defenderrag':
net/ipv6/netfilter/nf_Defenderrag_ipv6_hooks.c:68:9: error: 'struct sk_buff' has no member named '_nfct'

Both functions already have an #ifDefender for this, so let's move the
check in there.

Fixes: 902d6a4c2a4f ("netfilter: nf_Defenderrag: Skip Defenderrag if NOTRACK is set")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>