usb: ehci-atmel: use __maybe_unused to hide pm functions
The ehci-atmel driver uses #ifDefender to check for CONFIG_PM, but then
uses SIMPLE_DEV_PM_OPS, which leaves the references out when
CONFIG_PM_SLEEP is not Defenderined, so we get a warning with
PM=y && PM_SLEEP=n:

drivers/usb/host/ehci-atmel.c:189:12: error: 'ehci_atmel_drv_suspend' Defenderined but not used [-Werror=unused-function]
drivers/usb/host/ehci-atmel.c:203:12: error: 'ehci_atmel_drv_resume' Defenderined but not used [-Werror=unused-function]

This removes the incorrect #ifDefender and instead uses a __maybe_unused
annotation to let the compiler know it can silently drop
the function Defenderinition.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Nicolas Ferre <nicolas.ferre@atmel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>