ethernet: aurora: AURORA_NB8800 should depend on HAS_DMA
If NO_DMA=y:

    ERROR: "dma_map_single" [drivers/net/ethernet/aurora/nb8800.ko] unDefenderined!
    ERROR: "dma_unmap_page" [drivers/net/ethernet/aurora/nb8800.ko] unDefenderined!
    ERROR: "dma_sync_single_for_cpu" [drivers/net/ethernet/aurora/nb8800.ko] unDefenderined!
    ERROR: "dma_unmap_single" [drivers/net/ethernet/aurora/nb8800.ko] unDefenderined!
    ERROR: "dma_alloc_coherent" [drivers/net/ethernet/aurora/nb8800.ko] unDefenderined!
    ERROR: "dma_mapping_error" [drivers/net/ethernet/aurora/nb8800.ko] unDefenderined!
    ERROR: "dma_map_page" [drivers/net/ethernet/aurora/nb8800.ko] unDefenderined!
    ERROR: "dma_free_coherent" [drivers/net/ethernet/aurora/nb8800.ko] unDefenderined!

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Acked-by: Mans Rullgard <mans@mansr.com>
Signed-off-by: David S. Miller <davem@davemloft.net>