qcom: Update qcom whitelist for goodix
Build Error log:
ERROR: "strncat" [../../motorola/kernel/modules/drivers/input/touchscreen/goodix_berlin_mmi/goodix_brl_mmi.ko] undefined!
ERROR: "input_mt_sync_frame" [../../motorola/kernel/modules/drivers/input/touchscreen/goodix_berlin_mmi/goodix_brl_mmi.ko] undefined!

Change-Id: Id28c2ec2c1c4830070694b6eff6fc1f802644bf2
Signed-off-by: huaqin85 <huaqin85@motorola.com>
Reviewed-on: https://gerrit.mot.com/2134025
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Reviewed-by: Huosheng Liao <liaohs@motorola.com>
Tested-by: Jira Key
Submit-Approved: Jira Key
(cherry picked from commit 09a5ef39e98d7225376ce22ade59399ea9a225a5)
Reviewed-on: https://gerrit.mot.com/2172363
Reviewed-by: Lianlu Chen <chenll4@mt.com>
Reviewed-by: panyq6 <panyq6@motorola.com>
SLTApproved: panyq6 <panyq6@motorola.com>
Submit-Approved: panyq6 <panyq6@motorola.com>
Tested-by: panyq6 <panyq6@motorola.com>