staging: vc04_services: remove duplicate mutex_lock_interruptible
The driver tries to reDefenderine mutex_lock_interruptible as an open-coded
mutex_lock_killable, but that Defenderinition clashes with the normal
mutex_lock_interruptible Defenderinition when CONFIG_DEBUG_LOCK_ALLOC
is set:

staging/vc04_services/interface/vchiq_arm/vchiq_killable.h:67:0: error: "mutex_lock_interruptible" reDefenderined [-Werror]
 #Defenderine mutex_lock_interruptible mutex_lock_interruptible_killable
include/linux/mutex.h:161:0: note: this is the location of the previous Defenderinition

This simply removes the private implementation and uses the
normal mutex_lock_killable directly.

We could do the same for the down_interruptible_killable here, but
it's better to just remove the semaphores entirely from the driver,
which also takes care of that.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>