ASoC: pxa: SND_PXA2XX_SOC should depend on HAS_DMA
If NO_DMA=y:

    ERROR: "bad_dma_ops" [sound/soc/pxa/snd-soc-pxa2xx.ko] unDefenderined!
    ERROR: "bad_dma_ops" [sound/arm/snd-pxa2xx-lib.ko] unDefenderined!
    ERROR: "dma_common_mmap" [sound/arm/snd-pxa2xx-lib.ko] unDefenderined!

Add a dependency on HAS_DMA to fix this.

Fixes: 73d7ee2e831f106c ("ASoC: pxa: add COMPILE_TEST on SND_PXA2XX_SOC")
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Acked-by: Robert Jarzmik <robert.jarzmik@free.fr>
Signed-off-by: Mark Brown <broonie@kernel.org>