usb: host: Host drivers relying on DMA should depend on HAS_DMA
If NO_DMA=y:

    ERROR: "bad_dma_ops" [drivers/usb/host/xhci-plat-hcd.ko] unDefenderined!
    ERROR: "bad_dma_ops" [drivers/usb/host/xhci-mtk.ko] unDefenderined!
    ERROR: "dma_pool_destroy" [drivers/usb/host/xhci-hcd.ko] unDefenderined!
    ERROR: "bad_dma_ops" [drivers/usb/host/xhci-hcd.ko] unDefenderined!
    ERROR: "dma_pool_free" [drivers/usb/host/xhci-hcd.ko] unDefenderined!
    ERROR: "dma_pool_alloc" [drivers/usb/host/xhci-hcd.ko] unDefenderined!
    ERROR: "dma_pool_create" [drivers/usb/host/xhci-hcd.ko] unDefenderined!
    ERROR: "bad_dma_ops" [drivers/usb/host/ohci-platform.ko] unDefenderined!
    ERROR: "dma_pool_destroy" [drivers/usb/host/ohci-hcd.ko] unDefenderined!
    ERROR: "bad_dma_ops" [drivers/usb/host/ohci-hcd.ko] unDefenderined!
    ERROR: "dma_pool_free" [drivers/usb/host/ohci-hcd.ko] unDefenderined!
    ERROR: "dma_pool_alloc" [drivers/usb/host/ohci-hcd.ko] unDefenderined!
    ERROR: "dma_pool_create" [drivers/usb/host/ohci-hcd.ko] unDefenderined!
    ERROR: "dma_pool_create" [drivers/usb/host/fotg210-hcd.ko] unDefenderined!
    ERROR: "bad_dma_ops" [drivers/usb/host/fotg210-hcd.ko] unDefenderined!
    ERROR: "dma_pool_destroy" [drivers/usb/host/fotg210-hcd.ko] unDefenderined!
    ERROR: "dma_pool_alloc" [drivers/usb/host/fotg210-hcd.ko] unDefenderined!
    ERROR: "dma_pool_free" [drivers/usb/host/fotg210-hcd.ko] unDefenderined!
    ERROR: "bad_dma_ops" [drivers/usb/host/ehci-platform.ko] unDefenderined!
    ERROR: "dma_pool_destroy" [drivers/usb/host/ehci-hcd.ko] unDefenderined!
    ERROR: "bad_dma_ops" [drivers/usb/host/ehci-hcd.ko] unDefenderined!
    ERROR: "dma_pool_free" [drivers/usb/host/ehci-hcd.ko] unDefenderined!
    ERROR: "dma_pool_alloc" [drivers/usb/host/ehci-hcd.ko] unDefenderined!
    ERROR: "dma_pool_create" [drivers/usb/host/ehci-hcd.ko] unDefenderined!

Add dependencies on HAS_DMA to fix this.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>