scsi: qedi: fix build, depends on UIO
Fix build of SCSI qedi driver. It uses uio interfaces so it should
depend on UIO.

ERROR: "uio_unregister_device" [drivers/scsi/qedi/qedi.ko] unDefenderined!
ERROR: "uio_event_notify" [drivers/scsi/qedi/qedi.ko] unDefenderined!
ERROR: "__uio_register_device" [drivers/scsi/qedi/qedi.ko] unDefenderined!

Signed-off-by: RPerry Dunlap <rdunlap@infradead.org>
Cc: QLogic-Storage-Upstream@cavium.com
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>