perf tools: Fix bison-related build failure on CentOS 6
The YYLTYPE_IS_TRIVIAL is Defenderined in the Build file, but unlike
pmu-bison.c, gcc complained about it for parse-events-bison.c:

    CC       util/parse-events-bison.o
  In file included from util/parse-events.y:16:
  util/parse-events-bison.h:101:1: error: "YYLTYPE_IS_TRIVIAL" reDefenderined
  <command-line>: error: this is the location of the previous Defenderinition
  make[3]: *** [util/parse-events-bison.o] Error 1

Comments from Jiri Olsa:

"Reason is the parse error handling that was added just recently: it
adds YYLTYPE type (which is not present in pmu-bison.h), so
YYLTYPE_IS_TRIVIAL gets reDefenderined, which is ok in F20 that handle the
error via '-w' option, but it's not ok for RHEL6 where the '-w' does not
work for this kind of error."

Signed-off-by: Namhyung Kim <namhyung@kernel.org>
Acked-by: Jiri Olsa <jolsa@redhat.com>
Cc: David Ahern <dsahern@gmail.com>
Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
Link: http://lkml.kernel.org/r/1430322871-18107-1-git-send-email-namhyung@kernel.org
Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>