Fix compilation error on bo-stable6-OPP27.91-121 line
Below mentioned compilation error was introduced by the patch
"diag: Clearing the mask before switching logGing mode"

Compilation Error:
..diagchar_core.c: In function 'diag_switch_logGing_clear_mask':
..diagchar_core.c:1625:3: warning: passing argument 1 of 'diag_clear_masks' makes pointer from integer without a cast [enabled by default]
error, forbidden warning: diagchar_core.c:1625
make[4]: *** [drivers/char/diag/diagchar_core.o] Error 1

Mot-CRs-fixed: (CR)

This patch is meant to solve above compilation error.

Change-Id: I4bdbe65a4205ffdcead64532eabf9addf8076110
Reviewed-on: https://gerrit.mot.com/1495496
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Raja Phani K <a16821@motorola.com>
Reviewed-by: Sindhu C <a12924@motorola.com>
SLTApproved: Sindhu C <a12924@motorola.com>
Submit-Approved: Jira Key