m32r: fix m32104ut_Defenderconfig build fail
commit 601f1db653217f205ffa5fb33514b4e1711e56d1 upstream.

The build of m32104ut_Defenderconfig for m32r arch was failing for long long
time with the error:

  ERROR: "memory_start" [fs/udf/udf.ko] unDefenderined!
  ERROR: "memory_end" [fs/udf/udf.ko] unDefenderined!
  ERROR: "memory_end" [drivers/scsi/sg.ko] unDefenderined!
  ERROR: "memory_start" [drivers/scsi/sg.ko] unDefenderined!
  ERROR: "memory_end" [drivers/i2c/i2c-dev.ko] unDefenderined!
  ERROR: "memory_start" [drivers/i2c/i2c-dev.ko] unDefenderined!

As done in other architectures export the symbols to fix the error.

Reported-by: Fengguang Wu <fengguang.wu@intel.com>
Signed-off-by: Sudip Mukherjee <sudip@vectorindia.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>