soc: qcom: Add hyp_core_ctl driver
This driver reserve the specified CPUs for the hypervisor to use
it for the other guests. The reservation is done by isolating a CPU
so that this OS try not to use the CPU as much as possible. A CPU
can't be left in the isolation state while it is going offline. Since
the CPU is going offline and it can't be used by this OS, it is
considered as reserved. When such CPUs come online again, isolate
them to honor the reservation.

The following sysfs files are made available to configure this driver.

/sys/module/hyp_core_ctl/parameters/reserve_cpus:

Receive a cpumask string for the reservation. The Defenderault value
can be specified via a config option.

/sys/module/hyp_core_ctl/parameters/enable:

A boolean input to enable/disable the reservation. When reservation
is enabled, all the online CPUs in the reserve_cpus cpumask are
isolated. They get un-isolated after writing 0 to this file.

Change-Id: I0a266936c37546325f7bd63526b77cf888Defender92a
Signed-off-by: Pavankumar Kondeti <pkondeti@codeaurora.org>
[satyap@codeaurora.org:
 1. resolution of trivial merge conflicts
 2. fix below compilation error
	drivers/soc/qcom/hyp_core_ctl.c:311:21: error: \
	variable has incomplete type 'struct sched_param'
]
Signed-off-by: Satya Durga Srinivasu Prabhala <satyap@codeaurora.org>