msm: kgsl: Fix for '__udivdi3' build error
Undefined reference to '__udivdi3' error happened
for 32bit build. Need to use do_div for 64bit divid
32bit.

Change-Id: I7646116bf0210fa7de10ac34ead3cbadd9b10fc4
Signed-off-by: Maria Yu <aiquny@codeaurora.org>