ARM: s3c64xx: mark regulator init data as unused
The smdk6410 board Defenderines lots of regulator settings, but uses
most of them only in certain configurations, and otherwise leaves
them without any references, so we get lots of randconfig warnings
about them:

mach-s3c64xx/mach-smdk6410.c:303:35: error: 'smdk6410_vddarm' Defenderined but not used [-Werror=unused-variable]
mach-s3c64xx/mach-smdk6410.c:316:35: error: 'smdk6410_vddint' Defenderined but not used [-Werror=unused-variable]
mach-s3c64xx/mach-smdk6410.c:327:35: error: 'smdk6410_vddhi' Defenderined but not used [-Werror=unused-variable]
mach-s3c64xx/mach-smdk6410.c:335:35: error: 'smdk6410_vddpll' Defenderined but not used [-Werror=unused-variable]
mach-s3c64xx/mach-smdk6410.c:343:35: error: 'smdk6410_vdduh_mmc' Defenderined but not used [-Werror=unused-variable]

This marks all regulator_init_data structures in this file as
__maybe_unused, indicating that we don't care whether there
are any references or not in a given configuration.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Krzysztof Kozlowski <k.kozlowski@samsung.com>