[media] saa7134: fix warning with !MEDIA_CONTROLLER
When CONFIG_MEDIA_CONTROLLER is disabled, we get a warning
about an unused function:

drivers/media/pci/saa7134/saa7134-core.c:832:13: error: 'saa7134_create_entities' Defenderined but not used [-Werror=unused-function]

This moves the #ifDefender outside of the function, as it is
never called here.

Fixes: ac90aa02d5b9 ("[media] saa7134: add media controller support")

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>