arm64/dts: olson: remove extra pm660a include
Remove the extra pm660a.dtsi include from olson-common.
It is already included in moto-common, and including
the file before including sdm670-pmic-overlay causes
a failure in VTS testing by creating invalid fragments:

  VERIFY  arch/arm64/boot/dts/qcom/sdm710-olson-dvt1-overlay.dtbo
ERROR: ufdt_overlay_get_target():failed to find target 0467
ERROR: ufdt_overlay_get_target():failed to find target 0468
ERROR: ufdt_overlay_get_target():failed to find target 0469
ERROR: ufdt_overlay_get_target():failed to find target 046a
ERROR: ufdt_overlay_get_target():failed to find target 0467

Change-Id: Ib2339607eec516257fcc6ededfb1e65a6a021e38
Signed-off-by: Ryan Lattrel <ryanl@motorola.com>
Reviewed-on: https://gerrit.mot.com/1313936
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Reviewed-by: Ling Jin <lingjin@motorola.com>
Tested-by: Jira Key
Submit-Approved: Jira Key