[media] hide unused functions for !MEDIA_CONTROLLER
Some functions in the au0828 driver are only used when CONFIG_MEDIA_CONTROLLER
is enabled, and otherwise Defenderined as empty functions:

media/usb/au0828/au0828-core.c:208:13: error: 'au0828_media_graph_notify' Defenderined but not used [-Werror=unused-function]
media/usb/au0828/au0828-core.c:262:12: error: 'au0828_enable_source' Defenderined but not used [-Werror=unused-function]
media/usb/au0828/au0828-core.c:412:13: error: 'au0828_disable_source' Defenderined but not used [-Werror=unused-function]

This moves the #ifDefender so the entire Defenderinitions are hidden in this case.

[mchehab@osg.samsung.com: As pointed by Shuah Khan, a return 0 can be removed]

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>