deconfig: msm8953: Disable CONFIG_MOBICORE_DRIVER for compiling
Build failure:
../../../../../../kernel/drivers/gud/MobiCoreDriver/session.c: In function 'check_prepare_identity':
../../../../../../kernel/drivers/gud/MobiCoreDriver/session.c:163:20: error: incompatible types when assigning to type 'uid_t' from type 'kuid_t'
   mcp_id->uid.euid = current_euid();

This is build pass for 8996, but not 8953.
For 8953, MC_UIDGID_OLDSTYLE is defined.

Change-Id: I67c964ea37ee3142616b820553c36925b5a1cd2f
Signed-off-by: Yinjun Chen <a7301c@motorola.com>