Revert "ARM: dts: msm: Add a new display panel support for SDM710 QRD"
This reverts commit 0d92314d85c8edc4f587e93843791f1697587954.
Which causes the following build failure:
++++
arch/arm64/boot/dts/qcom/sdm710-monmouth-evt1-overlay.dtbo: ERROR (duplicate_node_names): Duplicate node name /fragment@26/__overlay__/qcom,dsi-display@18
ERROR: Input tree has errors, aborting (use -f to force output)
make[3]: *** [arch/arm64/boot/dts/qcom/sdm710-monmouth-evt1-overlay.dtbo] Error 2
make[3]: *** Waiting for unfinished jobs....
arch/arm64/boot/dts/qcom/sdm710-olson-dvt1-overlay.dtbo: ERROR (duplicate_node_names): Duplicate node name /fragment@26/__overlay__/qcom,dsi-display@18
++++

Change-Id: Ib357017d42d7eaae9b849e188410f3530b943437
Signed-off-by: a7301c <a7301c@motorola.com>