Revert "(CR): berlin: add RTB config in user build for debug"
user build error
In file included from /localrepo/hudson/workspace/RRG31_berlin-ctcn_user_mr_r-qsm8350_release-keys_derivative/platform/kernel/msm-5.4/include/linux/io.h:14:\n'
b"/localrepo/hudson/workspace/RRG31_berlin-ctcn_user_mr_r-qsm8350_release-keys_derivative/platform/kernel/msm-5.4/arch/arm64/include/asm/io.h:127:9:
error: 'writeq_relaxed' macro redefined [-Werror,-Wmacro-redefined]\n" b'#define writeq_relaxed(v,c)     ((void)__raw_writeq((__force u64)cpu_to_le64(v),(c)))\n' b' ^\n'
b'/localrepo/hudson/workspace/RRG31_berlin-ctcn_user_mr_r-qsm8350_release-keys_derivative/platform/kernel/msm-5.4/include/linux/msm_rtb.h:160:9:
note: previous definition is here\n' b'#define writeq_relaxed(v, c) \\\n' b'        ^\n' b'8 errors generated.\n'
make[6]: *** [/localrepo/hudson/workspace/RRG31_berlin-ctcn_user_mr_r-qsm8350_release-keys_derivative/platform/kernel/msm-5.4/scripts/Makefile.build:291: techpack/audio/asoc/codecs/wcd938x/wcd938x-mbhc.o] Error

This reverts commit 04d065dcbcb4ccd155d2b28680ebe9a63b6804b8.

Change-Id: I0c13749fa3753a35430ffd3b737af78f6851534f
Reviewed-on: https://gerrit.mot.com/1943234
Reviewed-by: Jichao Zou <zoujc@motorola.com>
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Submit-Approved: Jira Key