i2c: I2C_MT65XX should depend on HAS_DMA
If NO_DMA=y:

    ERROR: "dma_unmap_single" [drivers/i2c/busses/i2c-mt65xx.ko] unDefenderined!
    ERROR: "dma_mapping_error" [drivers/i2c/busses/i2c-mt65xx.ko] unDefenderined!
    ERROR: "dma_map_single" [drivers/i2c/busses/i2c-mt65xx.ko] unDefenderined!

Add a dependency on HAS_DMA to fix this.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Signed-off-by: Wolfram Sang <wsa@the-dreams.de>