staging: wilc1000: fix build error for openrisc-allmodconfig
The kbuild test robot reports the following build error for
openrisc-allmodconfig.

>> drivers/staging/wilc1000/wilc_sdio.c:584:2: error: implicit
>> declaration of function 'memset'

The error occurs due to missing a standard header file as
<linux/string.h> so that three .c files are included it.

Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Chaehyun Lim <chaehyun.lim@gmail.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>