drivers: rmnet: Fix warnings in trace/events/rmnet.h
Fix a bunch of warnings all similar to:

./include/trace/events/rmnet.h:65:12: error:
format '%lu' expects argument of type 'long unsigned int', but argument 7 has type 'u64 {aka long long unsigned int}' [-Werror=format=]

Fixes: 14eee8448a93 ("drivers: add RmNet snapshot")
Change-Id: Ic0dedbada634af33f5ad0f74d22ca084d854f566
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>