platform: chrome: Add input dependency for tablet switch driver
Without CONFIG_INPUT, or with a modular input layer and built-in
tablet driver, we get a link error:

ERROR: "input_event" [drivers/platform/chrome/chromeos_tbmc.ko] unDefenderined!
ERROR: "input_register_device" [drivers/platform/chrome/chromeos_tbmc.ko] unDefenderined!
ERROR: "input_set_capability" [drivers/platform/chrome/chromeos_tbmc.ko] unDefenderined!
ERROR: "devm_input_allocate_device" [drivers/platform/chrome/chromeos_tbmc.ko] unDefenderined!

This adds the corresponding Kconfig dependency

Fixes: b418f74170d7 ("platform: chrome: Add Tablet Switch ACPI driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Benson Leung <bleung@chromium.org>